### PR TITLE
helm: Keep CRD by default so druid clusters are not automatically rem…

### PR DESCRIPTION
**Pull request by jwitko**
### Description
Currently if the druid operator is installed with CRDs via the helm chart and then the helm chart is uninstalled then the CRDs are removed and all druid clusters would be destroyed.
This PR defaults to keeping the CRDs on helm chart uninstall and allows the user to configure the option to not.

This PR has:
- [X] been tested on a real K8S cluster to ensure creation of a brand new Druid cluster works.
- [X] been tested for backward compatibility on a real K*S cluster by applying the changes introduced here on an existing Druid cluster. If there are any backward incompatible changes then they have been noted in the PR description.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added documentation for new or modified features or behaviors.

##### Key changed/added files in this PR
 * `CRDs`

### CODE REVIEW

**Comment by AdheipSingh** [comment]
@jwitko thanks

**Review by AdheipSingh — APPROVED** [review]

**Comment by jrigassio** [comment]
great change! would like to see this go in as I just hit this problem today.

**Review by jrigassio — APPROVED** [review]

**Comment by AdheipSingh** [comment]
@jwitko i am tracking all your PR's and issues, will add them to https://github.com/cloudnativelyhq/druid-operator. 
I plan to cut a release in the coming next week compatible with 1.25 k8s version. 

You can port these changes to the new repo. 

Thanks

**Comment by jwitko** [comment]
Cool! Let me know if you need me to just make the pr again in the new repo.  Happy to do it.  I can also make it so they are backwards compatible

**Comment by AdheipSingh** [comment]
@jwitko it would be great if you can PR to new repo. 
I plan to cut a release by end of this month.

**Comment by jwitko** [comment]
Closing because it was merged in new druid-operator fork [datainfrahq/druid-operator](https://github.com/datainfrahq/druid-operator/issues/6)

**Pull request closed without merging**
